conflict: [negative]
violence: [negative]
aborted state: [negative]
absolute poverty: [negative]
absolutism: [negative]
accelerators: [negative]
active discrimination: [negative]
adverse regime transition: [negative]
aggregating factors: [negative]
aggression: [negative]
all-out war: [negative]
aid weariness: [negative]
anarchic state: [negative]
anarchy: [negative]
armed conflict: [negative]
authoritarian: [negative]
autocracy: [negative]
balkanization: [negative]
black market: [negative]
brain drain: [negative]
bhutanization: [negative]
brinkmanship: [negative]
capital flight: [negative]
cartel: [negative]
chaos: [negative]
civil war: [negative]
clan-katura: [negative]
cleavage: [negative]
closed economy: [negative]
coercion: [negative]
coervice diplomacy: [negative]
collective violence: [negative]
combat: [negative]
complex emergency: [negative]
concentration camp: [negative]
congo effect: [negative]
conscription: [negative]
cost of conflict: [negative]
coup d'etat: [negative]
crimes against humanity: [negative]
crisis: [negative]
cult of personality: [negative]
demagogue: [negative]
desertification : [negative]
deterrence: [negative]
dictatorship: [negative]
disenfranchisement: [negative]
disguised unemployment: [negative]
divide and rule: [negative]
dominance: [negative]
dominant minorities: [negative]
early warning: [negative]
elite-dominated democracy: [negative]
empire: [negative]
enclave economies: [negative]
essentialism: [negative]
ethnic cleansing: [negative]
ethnic conflict: [negative]
ethnic war: [negative]
ethnocentrism: [negative]
ethnocide: [negative]
ethno-natioalism: [negative]
ethno-nationalists: [negative]
ethno-political conflicts: [negative]
ethno-sexual violence: [negative]
faction: [negative]
food: [negative]
food insecurity: [negative]
food security: [negative]
frozen democracy: [negative]
gender gap: [negative]
gender violence: [negative]
genocide: [negative]
gerrymander: [negative]
ghetto: [negative]
grievance: [negative]
guerilla warfare: [negative]
hidden unemployment: [negative]
humanitarian emergency: [negative]
income inequality: [negative]
indirect aggression: [negative]
institutional violence: [negative]
insurgency: [negative]
intermediate armed conflict: [negative]
internal conflict: [negative]
interntal security: [negative]
internally displaced person: [negative]
internally displaced persons: [negative]
internally displaced people: [negative]
intervention: [negative]
irredentism: [negative]
jobless growth: [negative]
junta: [negative]
killing field : [negative]
late warning: [negative]
level of visible security: [negative]
lustration: [negative]
malnutrition: [negative]
market failure: [negative]
militarization: [negative]
minor armed conflict: [negative]
mobilizing factors: [negative]
national liberation: [negative]
nationalism: [negative]
near-crisis: [negative]
near crisis: [negative]
neo-colonial dependence: [negative]
neo-colonialism: [negative]
noise: [negative]
one-party dominance: [negative]
peacekeeping forces: [negative]
peacekeeping mandate : [negative]
personal rule: [negative]
polarization: [negative]
political exclusion: [negative]
political disenfranchisement: [negative]
poverty gap: [negative]
propaganda: [negative]
protracted conflict: [negative]
protracted social conflict: [negative]
pyhrric victory: [negative]
radical: [negative]
recession: [negative]
refoulement: [negative]
refugee: [negative]
repression: [negative]
residual discrimination: [negative]
revolution: [negative]
revolutionary war: [negative]
rigid instituions: [negative]
rogue state: [negative]
secret police: [negative]
separatism: [negative]
societal collapse: [negative]
spoilers: [negative]
state collapse: [negative]
state failure: [negative]
state terror: [negative]
state terrorism: [negative]
stratified society: [negative]
structural violence: [negative]
terrorism: [negative]
theocracy: [negative]
torture: [negative]
totalitarianism: [negative]
trigger: [negative]
unstable peace: [negative]
underdevelopment: [negative]
vicious cycle: [negative]
violent conflict: [negative]
vulnerable groups: [negative]
war: [negative]
war crimes: [negative]
war of succession: [negative]
willing executioners: [negative]